-- Run this in your Supabase SQL Editor

create table sponsors (
  id bigint generated by default as identity primary key,
  name text not null,
  city text,
  route text,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table sponsors enable row level security;

-- Create a policy that allows anyone to read the data (public access)
create policy "Enable read access for all users"
on sponsors for select
to anon
using (true);

-- Create an index on the name column for fast searching
create index sponsors_name_idx on sponsors using gin (name gin_trgm_ops);
-- Note: You might need to enable the pg_trgm extension first:
-- create extension if not exists pg_trgm;
